name: 'Filter Jobs by changed files'
author: 'Yuya Takeyama'

inputs:
  github-token:
    description: 'GitHub Token'
    default: ${{ github.token }}
  jobs:
    description: 'Jobs'
  root-dir:
    description: 'Root directory for dependency resolution'
    required: true

outputs:
  result:
    description: 'Filtered Jobs'

runs:
  using: 'node20'
  main: 'dist/index.js'
