name: 'Filter Jobs by changed files'
author: 'Yuya Takeyama'

inputs:
  github-token:
    description: 'GitHub Token'
    default: ${{ github.token }}
  jobs:
    description: 'Jobs'
  jobs-file:
    description: 'Path to a file containing Jobs JSON'

outputs:
  result:
    description: 'Filtered Jobs'
  result-file:
    description: 'Path to a file containing filtered Jobs JSON'

runs:
  using: 'node24'
  main: 'dist/index.js'
