name: 'Load Job Configs'
description: 'Load and filter Job Params from Local Config Files'
author: 'Yuya Takeyama'

inputs:
  root-dir:
    description: 'Root directory'
    required: true

outputs:
  result:
    description: 'Job Params'

runs:
  using: 'node20'
  main: 'dist/index.js'
