name: 'Load Jobs'
description: 'Load and filter Jobs from config files'
author: 'Yuya Takeyama'

inputs:
  workflow-id:
    description: 'Workflow ID'
    required: true
  root-dir:
    description: 'Root directory'
    required: true

outputs:
  result:
    description: 'Jobs'

runs:
  using: 'node20'
  main: 'dist/index.js'
