name: 'Load Jobs'
description: 'Load and filter Jobs from config files'
author: 'Yuya Takeyama'

inputs:
  root-dir:
    description: 'Root directory'
    required: true
  required-config-keys:
    description: 'Required config keys (comma separated)'
    required: true
  dedupe-key:
    description: 'Dedupe key to filter jobs. app path and job key are used together.'
    required: true
    # Default value:
    # - pull_request or pull_request_target: pr/{number}
    # - otherwise: github.ref (e.g. refs/heads/main)
    default: ${{ startsWith(github.event_name, 'pull_request') && format('pr/{0}', github.event.pull_request.number) || github.ref }}
  local-config-file-name:
    description: 'Local config file name'
    required: false
    default: 'monotonix.yaml'
  global-config-file-path:
    description: 'Global config file path for metadata validation schemas'
    required: false
    default: 'monotonix-global.yaml'

outputs:
  result:
    description: 'Jobs'

runs:
  using: 'node24'
  main: 'dist/index.js'
