name: 'Generate Docker build params'
description: 'Generate Docker build parameters for build matrix'
author: 'Yuya Takeyama'

inputs:
  root-dir:
    description: 'Root directory'
    required: true
  global-config-file:
    description: 'Global configuration file'
    required: true
  datetime-tag-timezone:
    description: 'Timezone for datetime tag'
    required: false
    default: 'UTC'

outputs:
  build-params:
    description: 'Build parameters'

runs:
  using: 'node20'
  main: 'dist/index.js'
