name: 'Load generic Job Params'
author: 'Yuya Takeyama'

inputs:
  config-key:
    description: 'Job Type to generate job params'
    required: true
  job-params:
    description: 'Job Params'

outputs:
  result:
    description: 'Job Params'

runs:
  using: 'node20'
  main: 'dist/index.js'
