name: 'Load Job Params for docker build'
author: 'Yuya Takeyama'

inputs:
  jobs:
    description: 'Jobs'
  global-config-file-path:
    description: 'Global config file path'
    required: true
  timezone:
    description: 'Timezone used to generate semver_datetime version'
    required: false
    default: 'UTC'

outputs:
  result:
    description: 'Jobs'

runs:
  using: 'node24'
  main: 'dist/index.js'
