name: 'Set DynamoDB state to running'
author: 'Yuya Takeyama'

inputs:
  dynamodb-table:
    description: 'DynamoDB Table'
    required: true
  dynamodb-region:
    description: 'DynamoDB Region'
    required: true
  job:
    description: 'Job'
    required: true
  ttl-in-days:
    description: 'TTL in days'
    required: false
  ttl-in-hours:
    description: 'TTL in hours'
    required: false
  ttl-in-minutes:
    description: 'TTL in minutes'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post/index.js'
