name: 'Filter Jobs by DynamoDB state'
author: 'Yuya Takeyama'

inputs:
  jobs:
    description: 'Jobs'
  jobs-file:
    description: 'Path to a file containing Jobs JSON'
  dynamodb-table:
    description: 'DynamoDB Table'
    required: true
  dynamodb-region:
    description: 'DynamoDB Region'
    required: true

outputs:
  result:
    description: 'Filtered Jobs'
  result-file:
    description: 'Path to a file containing filtered Jobs JSON'

runs:
  using: 'node24'
  main: 'dist/index.js'
